
CREATE TYPE subteam_names AS ENUM ('sportsman', 'kinetic', 'marketing', 'autonomous');

CREATE TABLE subteams (
    subteam_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subteam_name subteam_names
);