
CREATE TABLE builders (
    builder_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    builder_name TEXT,
    -- builder BELONGS TO subteam
    subteam_id BIGINT REFERENCES subteams(subteam_id)
);
--TODO: need another one for driver?