
CREATE TYPE weight_class AS ENUM ('3lb', '12lb');
CREATE TYPE weapon AS ENUM ('drum', 'vertical spinner', 'horizontal spinner');
CREATE TYPE drive AS ENUM ('walker', '2 wheel', '4 wheel');

CREATE TABLE robots (
    robot_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    robot_name TEXT NOT NULL,
    -- placed here instead of in builder table, because robot BELONGS TO builder
    builder_id BIGINT REFERENCES builders( builder_id ) NULL,
    weight_class weight_class NULL,
    weapon weapon NULL,
    drive drive NULL, 
    top_speed BIGINT, --all types except your own defined types/foreign keys are nullable by default
    weapon_speed BIGINT
);