
CREATE TYPE outcome_type AS ENUM ('KO', 'Judges Decision', 'Tapout');

CREATE TABLE fights (
    fight_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- foreign key: links to robot_id column in robots table
    -- placed here instead of in robots table, because fights BELONGS TO robot
    robot_id BIGINT REFERENCES robots(robot_id),
    opponent_name TEXT, --prob change this to another table if wanna query opponent info
    cage BIGINT,
    fight_time BIGINT, 
    last_updated BIGINT, 
    -- 1 if OUR robot has won
    is_win BOOLEAN,
    fight_duration BIGINT,
    outcome_type outcome_type
);