CREATE TYPE builders (
    builder_id BIGINT GENERATED BY DEFAULT AS PRIMARY KEY,
    builder_name TEXT,
    -- builder BELONGS TO subteam
    subteam_id REFERENCES subteam(subteam_id)
);
--TODO: need another one for driver?